language: node_js
node_js:
  - '7'
  - '8'
  - '9'
  - '10'
  - 'lts/*'
before_script:
  - npm install react@latest react-dom@latest
scripts:
  - npm install codecov -g
after_success:
  - npm run test:coverage
  - codecov -f coverage/*.json
